# vim: set filetype=yaml :

name: main
windows:
  - main:
      root: ~/dev
      layout: main-horizontal
      panes:
        - clear
        - clear
  - secondary:
      root: ~/dev
      panes:
        - clear

