# vim: set filetype=yaml :

name: main
windows:
  - vim:
      layout: main-horizontal
      root: ~/dev
      panes:
        - clear
        - clear
  - terminal:
      root: ~/dev
      panes:
        - clear
  - org:
      root: ~/zettelkasten
      panes:
        - v

