---
output_path: "~/dotfiles/out"
templates_path: "~/dotfiles"
repository: "git@github.com:samuelraub/dotfiles.git"
files:
  - name: .zshrc
    variants:
      - name: local
        links:
          - .zshrc
      - name: server
  - name: .zprofile
    variants:
      - name: local
        links:
          - .zprofile
  - name: .tmux.conf
    variants:
      - name: default
        links:
          - .tmux.conf
  - name: .vimrc
    variants:
      - name: local
        links:
          - .vimrc
      - name: server
  - name: .tmuxinator.yml
    variants:
      - name: local
        links:
          - .tmuxinator.yml
  - name: .kmonad.kbd
    variants:
      - name: local
        links:
          - .kmonad.kbd
  - name: kitty
    compile: false
    variants:
      - name: default
        links:
          - .config/kitty
  - name: mise
    compile: false
    variants:
      - name: default
        links:
          - .config/mise
  - name: gitignore
    compile: false
    variants:
      - name: default
        links:
          - .config/git/ignore
  - name: Brewfile
    compile: false
    variants:
      - name: default
  - name: borgmatic
    compile: false
    variants:
      - name: local
        links:
          - .config/borgmatic/config.yaml
  - name: borgmatic-run
    compile: false
    variants:
      - name: local
        links:
          - .local/bin/borgmatic-run
  - name: local.borgmatic.home.plist
    compile: false
    variants:
      - name: local
        links:
          - Library/LaunchAgents/local.borgmatic.home.plist
secrets:
  - .zshrc.local.secrets
