# vim: set filetype=toml.erb:

live_config_reload = true

[env]
TERM = "xterm-256color"

[shell]
program = "/bin/zsh"
args = ["--login", "-c", "tmuxinator"]

[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 0.97
startup_mode = "Maximized"

[window.padding]
x = 10
y = 8

[font]
size = 15.0

[font.normal]
family = "Dank Mono"
style = "Regular"

[font.bold]
family = "Dank Mono"
style = "Regular"

[font.italic]
family = "Dank Mono"
style = "Italic"


# Colors (Gruvbox Material Medium Dark)

# Default colors
[colors.primary]
background = '#282828'
foreground = '#d4be98'

# Normal colors
[colors.normal]
black   = '#3c3836'
red     = '#ea6962'
green   = '#a9b665'
yellow  = '#d8a657'
blue    = '#7daea3'
magenta = '#d3869b'
cyan    = '#89b482'
white   = '#d4be98'

# Bright colors (same as normal colors)
[colors.bright]
black   = '#3c3836'
red     = '#ea6962'
green   = '#a9b665'
yellow  = '#d8a657'
blue    = '#7daea3'
magenta = '#d3869b'
cyan    = '#89b482'
white   = '#d4be98'
