[settings]
experimental = true
idiomatic_version_file_enable_tools = []

[tools]
"gem:ruby-lsp" = "0.26.11"
go = "1.24.13"
"go:github.com/mark3labs/mcphost" = "0.33.2"
"go:golang.org/x/tools/gopls" = "0.20.0"
marksman = "2024-12-18"
node = "20"
"npm:@biomejs/biome" = "2.2.0"
"npm:@fsouza/prettierd" = "0.26.1"
"npm:@microsoft/compose-language-service" = "0.4.0"
"npm:@tailwindcss/language-server" = "0.14.26"
"npm:@vtsls/language-server" = "0.2.9"
"npm:dockerfile-language-server-nodejs" = "0.14.1"
"npm:vscode-langservers-extracted" = "4.10.0"
"npm:yaml-language-server" = "1.18.0"
"npm:yarn" = "1.22.22"
pnpm = "10.17.1"
python = "3.13.16"
ruby = "3.4.11"
terraform = "1.13.1"
